[package]
name = "pants-gen"
version = "0.1.0"
edition = "2021"
description = "A password generator used with pants."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
